#!/usr/bin/env python

import rospy
from std_srvs.srv import Trigger

class TsukubaChallengeStrategy:
    def __init__(self):
        rospy.init_node('tsukuba_challenge_strategy')
        self.start_nav_server = rospy.Service('start_nav', Trigger, self.start_nav_callback)
        
        suspend_pose = rospy.get_param('~suspend_pose')
        resume_pose = rospy.get_param('~resume_pose')

        print "suspend_pose = " + str(suspend_pose)
        print "resume_pose = " + str(resume_pose)

    def start_nav_callback(self, req):
        try:
            rospy.loginfo("strategy: start_nav_callback")
            rospy.wait_for_service('start_wp_nav')
            start_wp_nav = rospy.ServiceProxy('start_wp_nav', Trigger)
            return start_wp_nav()
            #rospy.loginfo(start_wp_nav())
            #return (True, "successful")
        except rospy.ServiceException, e:
            print "error: %s" % e

    def spin(self):
        rospy.spin()

if __name__ == '__main__':
    strategy = TsukubaChallengeStrategy()
    strategy.spin()

