- git:
    uri: https://github.com/open-rdc/icart_mini_ros_pkgs
    local-name: icart_mini_ros_pkgs
    version: master
- git:
    uri: https://github.com/open-rdc/t_frog_driver
    local-name: t_frog_driver
    version: master
- git:
    uri: https://github.com/open-rdc/icart_mini_gazebo
    local-name: icart_mini_gazebo
    version: master
- git:
    uri: https://github.com/open-rdc/t_frog_navigation
    local-name: t_frog_navigation
    version: master

