#!/usr/bin/env bash

# Author : Daiki Maekawa

echo ""
echo "Create robot parameters for ypspur"
echo ""

sudo cp `rospack find orne_setup`/config/icart-mini.param /usr/local/share/robot-params/icart-mini.param

