#!/usr/bin/env bash

# Author : Daiki Maekawa

echo ""
echo "Create robot parameters for ypspur"
echo ""

PARAM=${1:-icart-mini.param}
MIDDLE=${1:-icart-middle.param}
echo "PARAM_FILE_NAME = $PARAM,$MIDDLE"

sudo mkdir /usr/local/share/robot-params
sudo cp `rospack find orne_setup`/config/$PARAM /usr/local/share/robot-params/$PARAM
sudo cp `rospack find orne_setup`/config/$MIDDLE /usr/local/share/robot-params/$MIDDLE
