#!/usr/bin/env bash

# Author : Daiki Maekawa

echo ""
echo "Create robot parameters for ypspur"
echo ""

PARAM=${1:-/config/icart-mini.param}
find `rospack find orne_setup`$PARAM | sudo cpio -pdu /usr/local/share/robot-params
